In [28]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model, datasets

In [48]:
diabetes = datasets.load_diabetes()
diabetes_X = diabetes.data[:, np.newaxis, 2]
dia_X_train = diabetes_X[:-20]
dia_X_test = diabetes_X[-20:]

In [49]:
dia_y_train = diabetes.target[:-20]
dia_y_test = diabetes.target[-20:]

In [50]:
X_train = np.array([[1],[2],[3],[4],[5]])
y_train = np.array([[0.5],[1],[2.0],[2.5],[4.5]])

In [85]:
def gradDesc(X, y, y_pred, theta):
    error0 = (y_pred - y) * X[:,0]
    error1 = (y_pred - y) * X[:,1]
    theta[0][0] = theta[0][0] - 0.01 * (1.0/y.size) * error0.sum()
    theta[0][1] = theta[0][1] - 0.01 * (1.0/y.size) * error1.sum()
    return theta

In [86]:
def fit(X, y,num_iter=1000):
    theta = np.zeros([1, 2])
    x_int = np.ones([y.size, 2])
    x_int[:,1] = X[:,0]
    for i in range(num_iter):
        y_pred = np.zeros([1, y.size])
        for j in range(X.size):
            y_pred[0][j] = np.dot(theta,x_int[j])
        theta = gradDesc(x_int, y, y_pred, theta)
    return theta

In [87]:
def predict(X, theta):
    y_pred = np.zeros([1, X.size])
    y_int = np.ones([X.size, 2])
    y_int[:,1] = X[:,0]
    l = []
    for i in X:
        x = np.array([1, i])
        l.append(np.dot(theta,x))
    return l

In [88]:
theta = fit(dia_X_train, dia_y_train)
pred = predict(dia_X_test, theta)

In [89]:
theta

array([[ 153.34695384,   21.08033847]])

In [93]:
pres

array([ 225.9732401 ,  115.74763374,  163.27610621,  114.73638965,
        120.80385422,  158.21988574,  236.08568105,  121.81509832,
         99.56772822,  123.83758651,  204.73711411,   96.53399594,
        154.17490936,  130.91629517,   83.3878227 ,  171.36605897,
        137.99500384,  137.99500384,  189.56845268,   84.3990668 ])

In [94]:
print pred
plt.scatter(dia_X_train, dia_y_train, color='black')
plt.plot(dia_X_test, pred, color='red')
plt.plot(dia_X_test, pres, color='blue')
plt.show()

[array([ 154.9883404]), array([ 152.51179028]), array([ 153.57966052]), array([ 152.48906964]), array([ 152.6253935]), array([ 153.4660573]), array([ 155.21554683]), array([ 152.64811414]), array([ 152.14825999]), array([ 152.69355543]), array([ 154.51120689]), array([ 152.08009806]), array([ 153.37517473]), array([ 152.85259993]), array([ 151.78472969]), array([ 153.76142566]), array([ 153.01164443]), array([ 153.01164443]), array([ 154.17039724]), array([ 151.80745034])]


In [82]:
model = linear_model.LinearRegression()
model.fit(dia_X_train,dia_y_train)
pres = model.predict(dia_X_test)

In [83]:
model.coef_

array([ 938.23786125])

In [84]:
model.intercept_

152.91886182616167